@startuml Delete One Car (DELETE)

header Sameple RentalCarBooking Sequence Diagram
footer Page %page% of %lastpage%
title "Delete One Car (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:cars" as routerCars
participant "<<controllers>>\n:cars" as controllersCars
participant "<<model>>\n:Car" as modelCar
database "<<MongoDB>>\n:cars" as CarsDatabase

client->server ++:req.delete('/cars/:id')
server->routerCars ++:app.use('/cars',cars)
routerCars -> controllersCars ++:deleteCar ()
controllersCars->modelCar ++:Car.findById(req.params.id)
modelCar->CarsDatabase ++:CarSchema
CarsDatabase --> modelCar --: car
modelCar --> controllersCars --:  car
controllersCars->client --:response

@enduml